
services:
  helios:
    image: junoinnovations/helios:unstable-jammy
    hostname: "helios"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helios
    volumes:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd  # for AMD GPU's
      - .out/:/mnt/
    environment:
      - USER=helios
      - UID=5040
#      - IDLE_TIME=1
#      - PASSWORD=password
#      - PREFIX=/custom/prefix
    ports:
      - "3000:3000"
